#!/bin/sh
# Add org file changes to the repository
# thank you bernt hansen :D

for REPO in $1
do
    echo "Repository: $REPO"
    eval "cd $REPO"
    # Remove deleted files
    git ls-files --deleted -z | xargs -0 git rm >/dev/null 2>&1
    # Add new files
    git add . >/dev/null 2>&1
    git commit -m "$(date)"
done
echo Done
