#! /bin/bash

# super hacky script to ensure rofi always appears on the focused workspace

# current-output is a script from rofi-extras that outputs the xrandr name of
# screen showing the focused workspace
if name=$(current-output); then
    # putting the -m argument first should override any other -m arguments
    # later in the args list
    /usr/bin/rofi -m "$name" "$@"
else
    /usr/bin/rofi "$@"
fi
