#! /bin/sh

SPICE_PORT=5924

# use this to install virtio disk drivers after installation
# -drive file=$HOME/VirtualBox\ VMs/fake.qcow2,if=virtio \

# TODO make this work
# -net nic,model=virtio \

qemu-system-x86_64 \
    -enable-kvm \
    -cpu host \
    -smp 4 \
    -m 2G \
    -usb -device usb-tablet \
    -soundhw hda \
    -vga qxl \
    -drive file=/usr/share/virtio/virtio-win.iso,index=1,media=cdrom \
    -drive file=$HOME/VirtualBox\ VMs/test.img,format=raw,if=virtio

# qemu-system-x86_64 \
#     -enable-kvm \
#     -daemonize \
#     -smp 4 \
#     -m 2G \
#     -usb -device usb-tablet \
#     -soundhw hda \
#     -vga qxl \
#     -spice port=${SPICE_PORT},disable-ticketing \
#     -device virtio-serial \
#     -chardev spicevmc,id=vdagent,name=vdagent \
#     -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 \
#     VirtualBox\ VMs/test.img
# exec remote-viewer --title Windows spice://127.0.0.1:${SPICE_PORT}
