#!/bin/sh

# Convert all arguments (assumed SVG) to a PNG
# Requires Inkscape

for i in $@; do
  BN=$(basename $i .svg)
  inkscape --export-area-drawing --export-type=png --export-filename="$BN.png" --export-dpi 300 $i
done
